/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package xmobar-0.46 */
#ifndef VERSION_xmobar
#define VERSION_xmobar "0.46"
#endif /* VERSION_xmobar */
#ifndef MIN_VERSION_xmobar
#define MIN_VERSION_xmobar(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  46 || \
  (major1) == 0 && (major2) == 46 && (minor) <= 0)
#endif /* MIN_VERSION_xmobar */
/* package X11-1.10.3 */
#ifndef VERSION_X11
#define VERSION_X11 "1.10.3"
#endif /* VERSION_X11 */
#ifndef MIN_VERSION_X11
#define MIN_VERSION_X11(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  10 || \
  (major1) == 1 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_VERSION_X11 */
/* package X11-xft-0.3.4 */
#ifndef VERSION_X11_xft
#define VERSION_X11_xft "0.3.4"
#endif /* VERSION_X11_xft */
#ifndef MIN_VERSION_X11_xft
#define MIN_VERSION_X11_xft(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_X11_xft */
/* package aeson-2.0.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.0.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package async-2.2.4 */
#ifndef VERSION_async
#define VERSION_async "2.2.4"
#endif /* VERSION_async */
#ifndef MIN_VERSION_async
#define MIN_VERSION_async(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_async */
/* package base-4.16.4.0 */
#ifndef VERSION_base
#define VERSION_base "4.16.4.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  16 || \
  (major1) == 4 && (major2) == 16 && (minor) <= 4)
#endif /* MIN_VERSION_base */
/* package bytestring-0.11.3.1 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.11.3.1"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 3)
#endif /* MIN_VERSION_bytestring */
/* package cairo-0.13.8.2 */
#ifndef VERSION_cairo
#define VERSION_cairo "0.13.8.2"
#endif /* VERSION_cairo */
#ifndef MIN_VERSION_cairo
#define MIN_VERSION_cairo(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 8)
#endif /* MIN_VERSION_cairo */
/* package colour-2.3.6 */
#ifndef VERSION_colour
#define VERSION_colour "2.3.6"
#endif /* VERSION_colour */
#ifndef MIN_VERSION_colour
#define MIN_VERSION_colour(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_colour */
/* package containers-0.6.5.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.5.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_VERSION_containers */
/* package directory-1.3.6.2 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.6.2"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_directory */
/* package extensible-exceptions-0.1.1.4 */
#ifndef VERSION_extensible_exceptions
#define VERSION_extensible_exceptions "0.1.1.4"
#endif /* VERSION_extensible_exceptions */
#ifndef MIN_VERSION_extensible_exceptions
#define MIN_VERSION_extensible_exceptions(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_extensible_exceptions */
/* package filepath-1.4.2.2 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.2"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */
/* package http-client-tls-0.3.6.1 */
#ifndef VERSION_http_client_tls
#define VERSION_http_client_tls "0.3.6.1"
#endif /* VERSION_http_client_tls */
#ifndef MIN_VERSION_http_client_tls
#define MIN_VERSION_http_client_tls(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_http_client_tls */
/* package http-conduit-2.3.8 */
#ifndef VERSION_http_conduit
#define VERSION_http_conduit "2.3.8"
#endif /* VERSION_http_conduit */
#ifndef MIN_VERSION_http_conduit
#define MIN_VERSION_http_conduit(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_http_conduit */
/* package http-types-0.12.3 */
#ifndef VERSION_http_types
#define VERSION_http_types "0.12.3"
#endif /* VERSION_http_types */
#ifndef MIN_VERSION_http_types
#define MIN_VERSION_http_types(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 3)
#endif /* MIN_VERSION_http_types */
/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */
/* package old-locale-1.0.0.7 */
#ifndef VERSION_old_locale
#define VERSION_old_locale "1.0.0.7"
#endif /* VERSION_old_locale */
#ifndef MIN_VERSION_old_locale
#define MIN_VERSION_old_locale(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_VERSION_old_locale */
/* package pango-0.13.8.2 */
#ifndef VERSION_pango
#define VERSION_pango "0.13.8.2"
#endif /* VERSION_pango */
#ifndef MIN_VERSION_pango
#define MIN_VERSION_pango(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 8)
#endif /* MIN_VERSION_pango */
/* package parsec-3.1.15.0 */
#ifndef VERSION_parsec
#define VERSION_parsec "3.1.15.0"
#endif /* VERSION_parsec */
#ifndef MIN_VERSION_parsec
#define MIN_VERSION_parsec(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 15)
#endif /* MIN_VERSION_parsec */
/* package parsec-numbers-0.1.0 */
#ifndef VERSION_parsec_numbers
#define VERSION_parsec_numbers "0.1.0"
#endif /* VERSION_parsec_numbers */
#ifndef MIN_VERSION_parsec_numbers
#define MIN_VERSION_parsec_numbers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_parsec_numbers */
/* package process-1.6.16.0 */
#ifndef VERSION_process
#define VERSION_process "1.6.16.0"
#endif /* VERSION_process */
#ifndef MIN_VERSION_process
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 16)
#endif /* MIN_VERSION_process */
/* package regex-compat-0.95.2.1 */
#ifndef VERSION_regex_compat
#define VERSION_regex_compat "0.95.2.1"
#endif /* VERSION_regex_compat */
#ifndef MIN_VERSION_regex_compat
#define MIN_VERSION_regex_compat(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  95 || \
  (major1) == 0 && (major2) == 95 && (minor) <= 2)
#endif /* MIN_VERSION_regex_compat */
/* package stm-2.5.0.2 */
#ifndef VERSION_stm
#define VERSION_stm "2.5.0.2"
#endif /* VERSION_stm */
#ifndef MIN_VERSION_stm
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_stm */
/* package time-1.11.1.1 */
#ifndef VERSION_time
#define VERSION_time "1.11.1.1"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  11 || \
  (major1) == 1 && (major2) == 11 && (minor) <= 1)
#endif /* MIN_VERSION_time */
/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */
/* package unix-2.7.2.2 */
#ifndef VERSION_unix
#define VERSION_unix "2.7.2.2"
#endif /* VERSION_unix */
#ifndef MIN_VERSION_unix
#define MIN_VERSION_unix(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  7 || \
  (major1) == 2 && (major2) == 7 && (minor) <= 2)
#endif /* MIN_VERSION_unix */
/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */

/* tool alex-3.2.7.1 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.2.7.1"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_alex */
/* tool gcc-11 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  0 || \
  (major1) == 11 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.2.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.2.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.2.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.2.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.26.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.26.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  26 || \
  (major1) == 2 && (major2) == 26 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-1.20.0 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.20.0"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.8 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.8"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.2.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.2.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.38 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.38"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  38 || \
  (major1) == 2 && (major2) == 38 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "xmobar-0.46-BmzY7ApYG7XEl719tptHcj"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "xmobar-0.46-BmzY7ApYG7XEl719tptHcj"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.46"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
